apiVersion: velero.io/v1
kind: Restore
metadata:
  namespace: oadp-operator
  name: example-restore
spec:
  backupName: example-backup
  includedNamespaces:
    - example-namespace
  restorePVs: true
